#!/bin/sh
#Version 210903.1

echo "[rcS] Start"
echo "Kathrein UFS913 Neutrino"

MODDIR=/lib/modules

insmod $MODDIR/e2_proc.ko

echo "[rcS] Init frontpanel"
insmod $MODDIR/kathrein_micom.ko #paramDebug=50
insmod $MODDIR/simu_button.ko

if [ -e /var/etc/.firstboot ]; then
   echo "Wait 1 minute" > /dev/vfd
   echo "[rcS] Wait 1 minute"
   rm /var/etc/.firstboot
   sleep 1
   touch /dev/.devfsd
else
   echo "LOAD 10" > /dev/vfd
   echo "[rcS] LOAD 10"
fi

/etc/init.d/mountvirtfs start

echo "[rcS] Starting DEBUG Interface"
/etc/init.d/mountall start
/etc/init.d/hostname start

/etc/init.d/autofs start

/sbin/ifconfig lo 127.0.0.1 up

echo "[rcS] Starting telnetd"
/usr/sbin/telnetd -l /bin/autologin

echo "[rcS] Init stmfb (LOAD 9)"
echo "LOAD 9" > /dev/vfd
insmod $MODDIR/stmcore-display-sti7105.ko
insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m::pal:cvbs:yuv

echo "[rcS] Loading modules"

if [ ! -e /lib/firmware/audio.elf ] || [ ! -e /lib/firmware/video.elf ]; then
   echo "[rcS] Firmware(s) missing!"
   echo "FW MISSING!" > /dev/vfd
   sleep 5
fi

echo "[rcS] Load video firmware (LOAD 8)"
echo "LOAD 8" > /dev/vfd
/bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
/bin/ustslave /dev/st231-0 /lib/firmware/video.elf > /dev/null

echo "[rcS] Load audio firmware (LOAD 7)"
echo "LOAD 7" > /dev/vfd
/bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
/bin/ustslave /dev/st231-1 /lib/firmware/audio.elf > /dev/null

echo "[rcS] Init embx (LOAD 6)"
echo "LOAD 6" > /dev/vfd
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
insmod $MODDIR/mme_host.ko transport0=shm

echo "[rcS] Init AVS (LOAD 5)"
echo "LOAD 5" > /dev/vfd
insmod $MODDIR/avs.ko type=stv6417

player=`cat /proc/stb/player/version`
echo "[rcS] Init player $player (LOAD 4)"
echo "LOAD 4" > /dev/vfd
insmod $MODDIR/mmelog.ko
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko
insmod $MODDIR/pseudocard.ko

echo "[rcS] Init frontends"
insmod $MODDIR/frontend_platform.ko
insmod $MODDIR/socket.ko
insmod $MODDIR/lnbh221.ko
insmod $MODDIR/lnb_pio.ko
insmod $MODDIR/lnb_a8293.ko
insmod $MODDIR/avl6222.ko # paramDebug=50

insmod $MODDIR/ufs913_cic.ko

insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
if [ $? -ne 0 ]; then
   insmod $MODDIR/pti.ko
   echo "[rcS] Simple pti"
else
   echo "[rcS] Full feature pti"
fi
insmod $MODDIR/stm_monitor.ko
insmod $MODDIR/stmsysfs.ko
insmod $MODDIR/stmdvb.ko

echo "[rcS] Init player2 (LOAD 3)"
echo "LOAD 3" > /dev/vfd
insmod $MODDIR/player2.ko discardlateframe=0
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko
insmod $MODDIR/silencegen.ko

insmod $MODDIR/bpamem.ko

if [ -e $MODDIR/exportfs.ko ]; then
   insmod $MODDIR/exportfs.ko
fi
if [ -e $MODDIR/cifs.ko ]; then
   insmod $MODDIR/cifs.ko
fi
if [ -e $MODDIR/ntfs.ko ]; then
   insmod $MODDIR/ntfs.ko
fi
if [ -e $MODDIR/tun.ko ]; then
   insmod $MODDIR/tun.ko
fi
if [ -e $MODDIR/usbserial.ko ]; then
   insmod $MODDIR/usbserial.ko
   if [ -e $MODDIR/ftdi.ko ]; then
      insmod $MODDIR/ftdi.ko
   fi
   if [ -e $MODDIR/pl2303.ko ]; then
      insmod $MODDIR/pl2303.ko
   fi
   if [ -e $MODDIR/ch341.ko ]; then
      insmod $MODDIR/ch341.ko
   fi
fi

echo "[rcS] Init remote control (LOAD 2)"
echo "LOAD 2" > /dev/vfd
/bin/evremote2 10 120 &

# Load module(s) from modules.extra
[ -f /var/etc/modules.extra ] && eval `sed -e 's/#.*//' -e '/^\s*$/d' -e 's/^\(.*\)/insmod \0;/' < /var/etc/modules.extra`

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "[rcS] Booting from NFS, do not set network"
else
   if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      HWADDR=`grep -E -o '[[:xdigit:]]{2}(:[[:xdigit:]]{2}){5}' /dev/mtd2`
      ifconfig eth0 down
      ifconfig eth0 hw ether $HWADDR
      /etc/init.d/networking stop
      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "[rcS] Starting DHCP"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
   fi
fi

echo -n "[rcS] Init WLAN: "
wlan=
if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
   echo "None."
else
   insmod $MODDIR/$wlan.ko
   echo "[rcS] $wlan WLAN"
#   echo "$wlan WLAN" > /dev/vfd
#   sleep 3
fi

echo "[rcS] Try and synchronise time (LOAD 1)"
echo "LOAD 1" > /dev/vfd
if [ -h /usr/sbin/ntpd ]; then
   echo "[rcS] Set internet time"
   (ntpd -n -p 0.europe.pool.ntp.org -q; /bin/fp_control -sst) &
#else
#   if [ -e /usr/sbin/time.sh ]; then
#      echo "[rcS] Use transponder time"
#      /usr/sbin/time.sh &
#   fi
fi

echo "[rcS] Init portmap & ftp"
/etc/init.d/portmap start
/etc/init.d/vsftpd start
/usr/sbin/inetd

# Do own extras
if [ -e /var/etc/ownscript.sh ]; then
   /var/etc/ownscript.sh &
fi

echo "LOAD Neutrino" > /dev/vfd
echo "[rcS] Loading Neutrino"

stfbcontrol a 255

until false
do
   echo "[rcS] Starting Neutrino ->"
   /usr/bin/neutrino
   rtv=$?
   echo "Neutrino ended <- RTV: " $rtv
   fp_control -i 17 0  # all icons off
   case "$rtv" in
      0) echo "[rcS] SHUTDOWN"
         echo "Shutdown" > /dev/vfd
         init 0;;
      1) echo "[rcS] REBOOT"
         echo "Reboot" > /dev/vfd
         init 6;;
      3) echo "[rcS] RESTART"
         echo "Neutrino Restart" > /dev/vfd
         ;;
      *) echo "[rcS] ERROR"
         echo "Error" > /dev/vfd
         init 6;;
   esac
done

#never reached
echo "[rcS] REBOOT UFS913"
echo "REBOOT" > /dev/vfd
reboot -f
