#!/bin/sh
#Version 210903.1

echo "[rcS] Start"
echo "Kathrein UFS913 Enigma2"

MODDIR=/lib/modules

insmod $MODDIR/e2_proc.ko

echo "[rcS] Init frontpanel"
insmod $MODDIR/kathrein_micom.ko #paramDebug=30

if [ -e /var/etc/.firstboot ]; then
   echo "config.plugins.remotecontroltype.rctype=20" >> /etc/enigma2/settings
   echo "Wait 1 minute" > /dev/vfd
   echo "[rcS] Wait 1 minute"
   rm /var/etc/.firstboot
   sleep 1
   touch /dev/.devfsd
else
   echo "LOAD 10" > /dev/vfd
   echo "[rcS] LOAD 10"
fi

/etc/init.d/mountvirtfs start

echo "[rcS] Starting DEBUG Interface"
/etc/init.d/mountall start
/etc/init.d/hostname start

/etc/init.d/autofs start

echo -n "[rcS] Starting telnetd "
autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
if [ ! $autologin ]; then
   /usr/sbin/telnetd -l /bin/autologin
   echo "with autologin"
else
   /usr/sbin/telnetd -l /bin/login
   echo "with normal login"
fi

echo "[rcS] Init stmfb (LOAD 9)"
echo "LOAD 9" > /dev/vfd
insmod $MODDIR/stmcore-display-sti7105.ko
#if grep -q "config.av.videoport=Scart" /etc/enigma2/settings; then
#   insmod $MODDIR/stmfb.ko display0=720x576-16@50:1m::pal:cvbs
#else
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:16m::pal:cvbs:rgb
#fi
echo "[rcS] Loading modules"

if [ ! -e /boot/audio.elf ] || [ ! -e /boot/video.elf ]; then
   echo "[rcS] Firmware(s) missing!"
   echo "FW MISSING!" > /dev/vfd
   sleep 5
fi

echo "[rcS] Load video firmware (LOAD 8)"
echo "LOAD 8" > /dev/vfd
/bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null

echo "[rcS] Load audio firmware (LOAD 7)"
echo "LOAD 7" > /dev/vfd
/bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null

echo "[rcS] Init embx (LOAD 6)"
echo "LOAD 6" > /dev/vfd
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
insmod $MODDIR/mme_host.ko transport0=shm

echo "[rcS] Init AVS (LOAD 5)"
echo "LOAD 5" > /dev/vfd
insmod $MODDIR/avs.ko type=stv6417

player=`cat /proc/stb/player/version`
echo "[rcS] Init player $player (LOAD 4)"
echo "LOAD 4" > /dev/vfd
insmod $MODDIR/mmelog.ko
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko
insmod $MODDIR/pseudocard.ko

echo "[rcS] Init frontends and CI"
insmod $MODDIR/frontend_platform.ko
insmod $MODDIR/socket.ko
insmod $MODDIR/lnbh221.ko
insmod $MODDIR/lnb_pio.ko
insmod $MODDIR/lnb_a8293.ko
insmod $MODDIR/avl6222.ko

insmod $MODDIR/ufs913_cic.ko

insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
if [ $? -ne 0 ]; then
   insmod $MODDIR/pti.ko
   echo "[rcS] Simple pti"
else
   echo "[rcS] Full feature pti"
fi
insmod $MODDIR/stm_monitor.ko
insmod $MODDIR/stmsysfs.ko
insmod $MODDIR/stmdvb.ko

echo "[rcS] Init player2 (LOAD 3)"
echo "LOAD 3" > /dev/vfd
insmod $MODDIR/player2.ko
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko
insmod $MODDIR/silencegen.ko

insmod $MODDIR/bpamem.ko

if [ -e /boot/bootlogo.mvi ]; then
   showiframe -p /boot/bootlogo.mvi &
fi
stfbcontrol a 0

if [ -e $MODDIR/exportfs.ko ]; then
   insmod $MODDIR/exportfs.ko
fi
if [ -e $MODDIR/cifs.ko ]; then
   insmod $MODDIR/cifs.ko
fi
if [ -e $MODDIR/ntfs.ko ]; then
   insmod $MODDIR/ntfs.ko
fi
if [ -e $MODDIR/tun.ko ]; then
   insmod $MODDIR/tun.ko
fi
if [ -e $MODDIR/usbserial.ko ]; then
   insmod $MODDIR/usbserial.ko
   if [ -e $MODDIR/ftdi.ko ]; then
      insmod $MODDIR/ftdi.ko
   fi
   if [ -e $MODDIR/pl2303.ko ]; then
      insmod $MODDIR/pl2303.ko
   fi
   if [ -e $MODDIR/ch341.ko ]; then
      insmod $MODDIR/ch341.ko
   fi
fi

echo "[rcS] Init frontpanel (LOAD 2)"
echo "LOAD 2" > /dev/vfd
insmod $MODDIR/simu_button.ko

echo "[rcS] Init remote control"
/bin/evremote2 10 120 &

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "[rcS] Booting from NFS, do not set network"
else
   if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      HWADDR=`grep -E -o '[[:xdigit:]]{2}(:[[:xdigit:]]{2}){5}' /dev/mtd2`
      ifconfig eth0 down
      ifconfig eth0 hw ether $HWADDR
      /etc/init.d/networking stop
      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "[rcS] Starting DHCP"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
   fi
fi
#Allow network to wake up and initialize
sleep 2
#Show IP address on frontpanel
#ip=`ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p'`
#echo "IP $ip" > /dev/vfd
#sleep 3

echo -n "[rcS] Init WLAN: "
wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
   echo "None."
else
   insmod $MODDIR/$wlan.ko
   echo "[rcS] $wlan WLAN"
#   echo "$wlan WLAN" > /dev/vfd
#   sleep 3
fi

# Start automount
if [ -e /etc/init.d/automount ]; then
   python /etc/init.d/automount &
fi

echo "[rcS] Do extras (LOAD 1)"
echo "LOAD 1" > /dev/vfd
# inadyn
inadyn=`cat /etc/enigma2/settings | grep systemoptions.inadyn | cut -d "=" -f2`
if [ ! $inadyn ] ||  [ ! -e /usr/bin/inadyn ]; then
   echo "[rcS] No inadyn"
else
   if [ -e /usr/bin/inadyn ]; then
      /usr/bin/inadyn &
   fi
fi
# OpenSSh daemon
openssh=`cat /etc/enigma2/settings | grep systemoptions.openssh | cut -d "=" -f2`
if [ ! $openssh ] || [ ! -e /etc/init.d/sshd ]; then
   echo "[rcS] No OpenSSH"
else
   if [ -e /etc/init.d/sshd ]; then
      (sleep 30; /etc/init.d/sshd start) &
   fi
fi

# Enable PKT plugins
if [ ! -e /tmp/reference.dat ] && [ -e /var/bin/reference.dat ]; then
   cp /var/bin/reference.dat /tmp
fi

echo "[rcS] Try and synchronise time"
#inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
# if [ ! $inettime ] && [ -e /sbin/ntpd ]; then
if [ -h /usr/sbin/ntpd ]; then
   echo "[rcS] Set internet time"
   (ntpd -n -p 0.europe.pool.ntp.org -q; /bin/fp_control -sst) &
#else
#   if [ -e /usr/sbin/time.sh ]; then
#      echo "[rcS] Use transponder time"
#      /usr/sbin/time.sh &
#   fi
fi

echo "[rcS] Init portmap & ftp"
/etc/init.d/portmap start
/etc/init.d/vsftpd start
/usr/sbin/inetd

# Do own extras
if [ -e /etc/ownscript.sh ]; then
   /etc/ownscript.sh &
fi

echo "LOAD Enigma2" > /dev/vfd
echo "[rcS] Loading Enigma2"

stfbcontrol a 255
export ENIGMA_DEBUG_LVL=3

until false
do
   echo "[rcS] Starting Enigma2 ->"
   /usr/local/bin/enigma2
   rtv=$?
   echo "[rcS] E2 ended <- return value: " $rtv
   fp_control -i 17 0  # all icons off
   case "$rtv" in
      0) echo "[rcS] Enigma2 ERROR"
         echo "Enigma2 ERROR" > /dev/vfd
         init 6;;
      1) echo "[rcS] Deep Standby"
         echo "Deep Standby" > /dev/vfd
         if [ -e /usr/local/share/enigma2/shutdown.mvi ]; then
            showiframe -p /usr/local/share/enigma2/shutdown.mvi &
         fi
         init 0;;
      2) echo "[rcS] REBOOT"
         echo "Reboot" > /dev/vfd
         init 6;;
      3) echo "[rcS] Enigma2 RESTART"
         echo "Enigma2 Restart" > /dev/vfd
         export ENIGMA_DEBUG_LVL=3
         echo "0" > /proc/progress
         if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
            showiframe -p /usr/local/share/enigma2/backdrop.mvi &
         else
            showiframe -p /boot/bootlogo.mvi &
         fi;;
      6) echo "[rcS] E2 DEBUG RESTART"
         echo "E2 Debug Restart" > /dev/vfd
         export ENIGMA_DEBUG_LVL=4
         echo "0" > /proc/progress
         if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
            showiframe -p /usr/local/share/enigma2/backdrop.mvi &
         else
            showiframe -p /boot/bootlogo.mvi &
         fi;;
      *) echo "[rcS] ERROR"
         echo "ERROR" > /dev/vfd
         init 6;;
   esac
done

#never reached
echo "[rcS] REBOOT UFS913"
echo "REBOOT" > /dev/vfd
reboot -f
