#!/bin/sh
#Version 201014.1

echo "[rcS] Start"
echo "Edision Argus VIP (fixed tuner) Neutrino"

MODDIR=/lib/modules

insmod $MODDIR/e2_proc.ko

echo "[rcS] Init frontpanel"
insmod $MODDIR/proton.ko #paramDebug=20
insmod $MODDIR/simu_button.ko
if [ -e $MODDIR/encrypt.ko ]; then
   insmod $MODDIR/encrypt.ko
fi

if [ -e /var/etc/.firstboot ]; then
   echo "WAIT 3 min" > /dev/vfd
   echo "[rcS] WAIT 3 minutes"
   rm /var/etc/.firstboot
   sleep 1
   touch /dev/.devfsd
else
   echo "Load 10" > /dev/vfd
   echo "[rcS] Start (LOAD 10)"
fi

/etc/init.d/mountvirtfs start
/etc/init.d/portmap start
/etc/init.d/autofs start

echo "[rcS] Starting DEBUG Interface"
/etc/init.d/mountall start
/etc/init.d/hostname start

echo "[rcS] Starting telnetd"
/usr/sbin/telnetd -l /bin/autologin

echo "[rcS] Init stmfb (LOAD 9)"
echo "Load 9" > /dev/vfd
insmod $MODDIR/stmcore-display-stx7109c3.ko
#insmod $MODDIR/stmfb.ko display0=720x576i-32@50:15m:0:pal:cvbs:rgb #SCART
insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:0:pal:cvbs:rgb #HDMI

echo "[rcS] Loading modules"

if [ ! -e /lib/firmware/audio.elf ] || [ ! -e /lib/firmware/video.elf ]; then
   echo "[rcS] FIRMWARE MISSING!"
   echo "FW MISSING!" > /dev/vfd
fi

echo "[rcS] Load video firmware (LOAD 8)"
echo "Load 8" > /dev/vfd
/bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096 2> /dev/null
/bin/ustslave /dev/st231-0 /lib/firmware/video.elf > /dev/null

echo "[rcS] Load audio firmware (LOAD 7)"
echo "Load 7" > /dev/vfd
/bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096 2> /dev/null
/bin/ustslave /dev/st231-1 /lib/firmware/audio.elf > /dev/null

echo "[rcS] Init embx (LOAD 6)"
echo "Load 6" > /dev/vfd
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000
insmod $MODDIR/mme_host.ko transport0=shm

echo "[rcS] Init AVS (LOAD 5)"
echo "Load 5" > /dev/vfd
insmod $MODDIR/avs.ko type=stv6418

player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
echo "[rcS] Init player $player (LOAD 4)"
echo "Load 4" > /dev/vfd
insmod $MODDIR/mmelog.ko
insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0;
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko
insmod $MODDIR/stmvout.ko
insmod $MODDIR/stmvbi.ko

insmod $MODDIR/pseudocard.ko

echo "[rcS] Init frontends"
#demodulator type: stb0899(default) stv090x
#tuner type: stb6100(default) stv6110x, sharp7306
insmod $MODDIR/fe-core.ko demod=stv090x tuner=stv6110x #paramDebug=50

insmod $MODDIR/cimax.ko #paramDebug=20
insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
if [ $? -ne 0 ]; then
   insmod $MODDIR/pti.ko
   echo "[rcS] Simple pti"
else
   echo "[rcS] Full feature pti"
fi
insmod $MODDIR/stm_monitor.ko
insmod $MODDIR/stmsysfs.ko
insmod $MODDIR/stmdvb.ko

echo "[rcS] LOAD 3"
echo "Load 3" > /dev/vfd
insmod $MODDIR/player2.ko
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko

insmod $MODDIR/smartcard.ko

if [ -e $MODDIR/exportfs.ko ]; then
   insmod $MODDIR/exportfs.ko
fi
if [ -e $MODDIR/cifs.ko ]; then
   insmod $MODDIR/cifs.ko
fi
if [ -e $MODDIR/ntfs.ko ]; then
   insmod $MODDIR/ntfs.ko
fi
if [ -e $MODDIR/tun.ko ]; then
   insmod $MODDIR/tun.ko
fi
if [ -e $MODDIR/usbserial.ko ]; then
  insmod $MODDIR/usbserial.ko
  if [ -e $MODDIR/ch341.ko ]; then
    insmod $MODDIR/ch341.ko
  fi
  if [ -e $MODDIR/ftdi.ko ]; then
    insmod $MODDIR/ftdi.ko
  fi
  if [ -e $MODDIR/pl2303.ko ]; then
    insmod $MODDIR/pl2303.ko
  fi
  if [ -e $MODDIR/option.ko ]; then
    insmod $MODDIR/option.ko
  fi
  if [ -e $MODDIR/usb_wwan.ko ]; then # 3G modem
    insmod $MODDIR/usb_wwan.ko
  fi
  insmod $MODDIR/option.ko
fi

insmod $MODDIR/bpamem.ko
mknod /dev/bpamem c 153 0

#if [ -e /boot/neutrinologo.mvi ]; then
#   showiframe -p /boot/neutrinologo.mvi &
#fi
stfbcontrol a 0

echo "[rcS] Init remote control (LOAD 2)"
echo "LOAD 2" > /dev/vfd
if [ ! -d /var/run/lirc ]; then
   mkdir -p /var/run/lirc
fi
/usr/bin/lircd
rm -rf /dev/rc
mknod /dev/rc c 147 1 #VFD
/bin/evremote2 10 120 &

echo "[rcS] Init smartcard cardreader"
mknod /dev/sci0 c 169 0
mknod /dev/sci1 c 169 1

stfbcontrol a 255

# Load modules from /var/etc/modules.extra
[ -f /var/etc/modules.extra ] && eval `sed -e 's/#.*//' -e '/^\s*$/d' -e 's/^\(.*\)/insmod \0;/' < /var/etc/modules.extra`

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "[rcS] Booting from nfs, do not set network"
else
   if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      MAC="12:34:56:78:9A:BC"
      ip link set eth0 address $MAC
      DHCP=`grep -c dhcp /etc/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "[rcS] Starting DHCP"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start &
   fi
fi

#wlan=rtl8188cu
if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
   echo "[rcS] No WLAN"
else
   insmod $MODDIR/$wlan.ko
   echo "[rcS] $wlan WLAN"
#   echo "$wlan WLAN" > /dev/vfd
#   sleep 3
fi

# Try and synchronise time
if [ -h /usr/sbin/ntpd ]; then
   echo "[rcS] Set internet time"
   (ntpd -n -p 0.europe.pool.ntp.org -q; /bin/fp_control -sst)
fi

echo "[rcS] Init portmap & ftp (LOAD 1)"
echo "Load 1" >/dev/vfd
/etc/init.d/portmap start
/etc/init.d/vsftpd start
/usr/sbin/inetd

echo "[rcS] Start neutrino"
echo "Loading Neutrino" > /dev/vfd

until false
do
#   killall -9 showiframe
   echo "[rcS] Starting neutrino ->"
   /usr/bin/neutrino
   rtv=$?
   echo "[rcS] Neutrino ended <- return value: " $rtv
   /bin/fp_control -i 46 0
   case "$rtv" in
      0) echo "[rcS] SHUTDOWN"
         echo "Shutdown" > /dev/vfd
         init 0;;
      1) echo "[rcS] REBOOT"
         echo "Reboot" > /dev/vfd
         init 6;;
      3) echo "[rcS] RESTART"
         echo "Restart" > /dev/vfd
         ;;
      *) echo "[rcS] ERROR"
         echo "Error" > /dev/vfd
         init 6;;
   esac
done

#never reached
echo "[rcS] REBOOT VIP V1"
echo "REBOOT" > /dev/vfd
init 6
