#!/bin/sh
#Version 160526.1

echo "Fortis HS7810A Tvheadend"

MODDIR=/lib/modules

insmod $MODDIR/e2_proc.ko

echo "[rcS] Init frontpanel"
if [ ! -e /dev/vfd ]; then
   mknod -m 0660 /dev/vfd c 147 0
fi
insmod $MODDIR/nuvoton.ko
insmod $MODDIR/simu_button.ko

if [ -e /var/etc/.firstboot ]; then
   echo "1min" > /dev/vfd
   echo "[rcS] WAIT 1 minute"
   rm /var/etc/.firstboot
   sleep 1
   touch /dev/.devfsd
else
   echo "LD10" > /dev/vfd
fi

/etc/init.d/mountvirtfs start

# Start automounter with umount timeout of 5 seconds
#mkdir /tmp/autofs
#if [ -e $MODDIR/autofs4.ko ]; then
#   insmod $MODDIR/autofs4.ko
#fi
#if [ -e /etc/init.d/automount ]; then
#   /usr/sbin/automount --timeout=5 --ghost /tmp/autofs file /etc/auto.usb
#fi

echo "[rcS] Starting DEBUG Interface"
/etc/init.d/mountall start
/etc/init.d/hostname start

echo -n "[rcS] Starting telnetd "
/usr/sbin/telnetd -l /bin/autologin
echo "with autologin"

echo "[rcS] Init stmfb (LOAD 9)"
echo "LD 9" > /dev/vfd
insmod $MODDIR/stmcore-display-sti7111.ko
insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:rgb:rgb

echo "[rcS] Loading modules"

if [ ! -e /lib/firmware/audio.elf ] || [ ! -e /lib/firmware/video.elf ]; then
   echo "[rcS] Firmware(s) missing!"
   echo "NOFW" > /dev/vfd
   sleep 5
fi

echo "[rcS] Load video firmware (LOAD 8)"
echo "LOAD 8" > /dev/vfd
/bin/ustslave /dev/st231-0 /lib/firmware/video.elf > /dev/null

echo "[rcS] Load audio firmware (LOAD 7)"
echo "Load 7" > /dev/vfd
/bin/ustslave /dev/st231-1 /lib/firmware/audio.elf > /dev/null

echo "[rcS] Init embx (LOAD 6)"
echo "LD 6" > /dev/vfd
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
insmod $MODDIR/mme_host.ko transport0=shm

echo "[rcS] Init AVS (LOAD 5)"
echo "LD 5" > /dev/vfd
insmod $MODDIR/avs.ko type=avs_pio

player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
echo "[rcS] Init player $player (LOAD 4)"
echo "LD 4" > /dev/vfd
insmod $MODDIR/mmelog.ko
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko
insmod $MODDIR/pseudocard.ko

echo "[rcS] Init frontend"
insmod $MODDIR/lnb.ko type=a8293
insmod $MODDIR/stv090x.ko paramDebug=0
mknod /dev/lnb c 149 0

insmod $MODDIR/starci.ko
insmod $MODDIR/smartcard.ko

insmod $MODDIR/pti.ko
insmod $MODDIR/stm_monitor.ko
insmod $MODDIR/stmsysfs.ko
insmod $MODDIR/stmdvb.ko

echo "[rcS] Init player2 (LOAD 3)"
echo "LD 3" > /dev/vfd
insmod $MODDIR/player2.ko
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko
insmod $MODDIR/silencegen.ko
insmod $MODDIR/bpamem.ko
mknod /dev/bpamem c 153 0

#echo "[rcS] Init HDMI-CEC"
#if [ -e $MODDIR/cec.ko ]; then
#   insmod $MODDIR/cec.ko activemode=1
#fi

if [ -e /boot/tvhlogo_720.mvi ]; then
   showiframe -p /boot/tvhlogo_720.mvi &
fi
stfbcontrol a 0

echo "[rcS] Init network (LOAD 2)"
echo "LD 2" >/dev/vfd

stfbcontrol a 255

#wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
#if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
#   echo "No WLAN"
#else
#   insmod $MODDIR/$wlan.ko
#   echo "$wlan WLAN"
##   echo "$wlan WLAN" > /dev/vfd
##   sleep 3
#fi

if [ -e $MODDIR/ntfs.ko ]; then
   insmod $MODDIR/ntfs.ko
fi

if [ -e $MODDIR/cifs.ko ]; then
   insmod $MODDIR/cifs.ko
fi

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "[rcS] Booting from nfs, don't set network"
else
   if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=`grep -c dhcp /etc/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "[rcS] Starting DHCP"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
   fi
fi
#Allow network to wake up and initialize
sleep 2
#Show last octet of IP address on frontpanel
ip=`ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p' | cut -d. -f4`
echo ".$ip" > /dev/vfd
sleep 3

#timefix tvheadend
date -s "201605011200"
# Try and synchronise time
if [ -e /sbin/ntpdate ]; then
   echo "Set internet time"
   (/sbin/ntpdate de.pool.ntp.org; /bin/fp_control -sst) &
else
   if [ -e /usr/sbin/time.sh ]; then
      echo "Use transponder time"
      /usr/sbin/time.sh &
   fi
fi

echo "[rcS] Init portmap & ftp (LOAD 1)"
echo "LOAD 1" > /dev/vfd
/etc/init.d/portmap start
/etc/init.d/vsftpd start
/usr/sbin/inetd

echo "Start Tvheadend" > /dev/vfd
echo "[rcS] Start Tvheadend"

until false
do
   echo "[rcS] Entering Tvheadend main loop"
   /usr/local/bin/tvheadend --http_port 80 -C
   rtv=$?
   echo "[rcS] Tvheadend ended <- RTV: " $rtv
   case "$rtv" in
      0) echo "SHUTDOWN"
         echo "Shdn" > /dev/vfd
         init 0;;
      1) echo "REBOOT"
         echo "rebt" > /dev/vfd
         init 6;;
      *) echo "ERROR"
         echo "Err " > /dev/vfd
         init 6;;
   esac
done

#never reached
echo "REBOOT Fortis HS7810A"
echo "REBOOT Fortis HS7810A" > /dev/vfd
reboot -f
