#!/bin/sh
#Version 210903.1

echo "[rcS] Start"
echo "Topfield TF77X0HDPVR Enigma2"

MODDIR=/lib/modules

rm -f /dev/vfd
rm -f /dev/rc
rm -f /dev/fpc
mknod -m 0666 /dev/fpc     c 62 0 2>/dev/null
mknod -m 0666 /dev/vfd     c 62 0 2>/dev/null
mknod -m 0666 /dev/rc      c 62 1 2>/dev/null
mknod -m 0666 /dev/fplarge c 62 2 2>/dev/null
mknod -m 0666 /dev/fpsmall c 62 3 2>/dev/null

insmod $MODDIR/e2_proc.ko

echo "[rcS] Init frontpanel"
insmod $MODDIR/tffp.ko
insmod $MODDIR/simu_button.ko
tffpctl --keyemulationmode 2

if [ -e /var/etc/.firstboot ]; then
   echo "config.plugins.remotecontroltype.rctype=11" >> /etc/enigma2/settings
   echo "WAIT" > /dev/fpsmall
   echo "3 minutes" > /dev/fplarge
   rm /var/etc/.firstboot
   touch /dev/.devfsd
else
   echo "LOAD" > /dev/fplarge
   echo "  10" > /dev/fpsmall
   echo "[rcS] LOAD 10"
fi

# remove /dev/ttyAS1 to avoid interference with the FP driver
if [ -e /dev/ttyAS1 ]; then
   rm -f /dev/ttyAS1
fi

# Update the GMT offset in case it changed during the standby
/bin/tffpctl --setgmtoffset

/etc/init.d/mountvirtfs start
/etc/init.d/portmap start

#/etc/init.d/autofs start

echo -n "[rcS] Starting telnetd "
autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
if [ ! $autologin ]; then
   /usr/sbin/telnetd -l /bin/autologin
   echo "with autologin"
else
   /usr/sbin/telnetd -l /bin/login
   echo "with normal login"
fi

echo "Loading modules"

echo "LOAD" > /dev/fplarge
echo "   9" > /dev/fpsmall
echo "[rcS] Init stmfb (LOAD 9)"
insmod $MODDIR/stmcore-display-stx7109c3.ko
insmod $MODDIR/stmfb.ko display0=1280x720-32@50:16m::pal:cvbs:rgb

if [ ! -e /boot/audio.elf ] || [ ! -e /boot/video.elf ]; then
   echo "[rcS] FIRMWARE MISSING!"
   echo "  FW" > /dev/fpsmall
   echo "MISSING!" > /dev/fplarge
fi

echo "[rcS] Load video firmware (LOAD 8)"
echo "   8" > /dev/fpsmall
bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null

echo "[rcS] Load audio firmware (LOAD 7)"
echo "   7" > /dev/fpsmall
dtsdown=`cat /etc/enigma2/settings | grep systemoptions.dtsdownmix | cut -d "=" -f2`
if [ ! $dtsdown ] && [ -e /boot/audio_dts.elf ]; then
   /bin/ustslave /dev/st231-1 /boot/audio_dts.elf > /dev/null
else
   /bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null
fi

echo "[rcS] Init embx (LOAD 6)"
echo "   6" > /dev/fpsmall
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000
insmod $MODDIR/mme_host.ko transport0=shm

echo "[rcS] Init AVS (LOAD 5)" 
echo "   5" > /dev/fpsmall
insmod $MODDIR/avs.ko type=stv6412

player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
echo "[rcS] Init player $player (LOAD 4)"
echo "   4" > /dev/fpsmall
insmod $MODDIR/mmelog.ko
insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER1
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko
insmod $MODDIR/pseudocard.ko

insmod $MODDIR/cx24116.ko

insmod $MODDIR/starci.ko
insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
if [ $? -ne 0 ]; then
   insmod $MODDIR/pti.ko
   echo "[rcS] Simple pti"
else
   echo "[rcS] Full feature pti"
fi
insmod $MODDIR/stm_monitor.ko
insmod $MODDIR/stmsysfs.ko
insmod $MODDIR/stmdvb.ko

echo "[rcS] Init eplayer2 (LOAD 3)"
echo "   3" > /dev/fpsmall
insmod $MODDIR/player2.ko
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko
insmod $MODDIR/silencegen.ko

insmod $MODDIR/bpamem.ko
mknod /dev/bpamem c 153 0

if [ -e /boot/bootlogo.mvi ]; then
   showiframe -p /boot/bootlogo.mvi &
fi
stfbcontrol a 0

# Workaround why is jfs always not mountable?
#fsck.ext3 /dev/sda3 -a
#fsck.jfs /dev/sda3 -a

echo "[rcS] Init remote control (LOAD 2)"
echo "   2" > /dev/fpsmall
insmod $MODDIR/boxtype.ko
insmod $MODDIR/tfswitch.ko
/bin/evremote2 110 10 &

stfbcontrol a 255

wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
   echo "[rcS] No WLAN"
else
   insmod $MODDIR/$wlan.ko
   echo "[rcS] $wlan WLAN"
#   echo "$wlan WLAN" > /dev/vfd
#   sleep 3
fi

#/etc/init.d/mountall start

#/etc/init.d/hostname start

if [ -e $MODDIR/ntfs.ko ]; then
   insmod $MODDIR/ntfs.ko
fi

if [ -e $MODDIR/cifs.ko ]; then
   insmod $MODDIR/cifs.ko
fi

echo "[rcS] Init FTP & network (LOAD 1)"
echo "   1" > /dev/fpsmall
/etc/init.d/vsftpd start
/usr/sbin/inetd

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "Booting from nfs, do not set network"
else
   if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "[rcS] Starting DHCP on eth0"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start &
   fi
fi
#Allow network to wake up and initialize
sleep 2
#Show IP address on frontpanel
#ip=`ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p'`
#echo "IP $ip" > /dev/vfd
#sleep 3

# Start automount
if [ -e /etc/init.d/automount ]; then
   python /etc/init.d/automount &
fi

# Do own extras
if [ -e /etc/ownscript.sh ]; then
   /etc/ownscript.sh &
fi

# Try and synchronise time
#inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
# if [ ! $inettime ] && [ -e /sbin/ntpd ]; then
if [ -h /usr/sbin/ntpd ]; then
   echo "[rcS] Set internet time"
   (ntpd -n -p 0.europe.pool.ntp.org -q; tffpctl --syncfptime)
#else
#   if [ -e /usr/sbin/time.sh ]; then
#      echo "[rcS] Use transponder time"
#      /usr/sbin/time.sh &
#   fi
fi

echo "[rcS] Start Enigma2"
echo "STRT" > /dev/fpsmall
echo "ENIGMA 2" > /dev/fplarge

until false
do
   echo "[rcS] Entering E2 main loop"
   if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
      showiframe -p /usr/local/share/enigma2/backdrop.mvi &
   fi
   /usr/local/bin/enigma2
   rtv=$?
   # update the GMT offset in case it changed while being turned on
   /bin/tffpctl --setgmtoffset
   /bin/tffpctl --cleardisplay
   echo "[rcS] e2 ended <- RTV: " $rtv
   case "$rtv" in
      0) echo "[rcS] E2 ERROR"
         echo "E2 ERROR" > /dev/fplarge
         #kill tuxtxt because it inhibits E2 from
         #restart after a crash. Of course this could
         #be done better ;-)
         /usr/bin/killall tuxtxt
         #rset
         showiframe -p /var/boot/bootlogo.mvi &
         echo "0" > /proc/progress;;
      1) echo "[rcS] DEEP STANDBY"
         echo "DEEP" > /dev/fpsmall
         echo "STANDBY" > /dev/fplarge
         if [ -e /usr/local/share/enigma2/shutdown.mvi ]; then
             showiframe -p /usr/local/share/enigma2/shutdown.mvi &
         fi
         init 0;;
      2) echo "[rcS] REBOOT"
         echo "REBOOT" > /dev/fplarge
         init 6;;
      3) echo "[rcS] E2 RESTART"
         echo " GUI" > /dev/fpsmall
         echo "RESTART" > /dev/fplarge
         if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
            showiframe -p /usr/local/share/enigma2/backdrop.mvi &
         else
            showiframe -p /boot/bootlogo.mvi &
         fi;;
      6) echo "[rcS] E2 DEBUG RESTART"
         echo " DBG" > /dev/fpsmall
         echo "RESTART" > /dev/fplarge
         if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
            showiframe -p /usr/local/share/enigma2/backdrop.mvi &
         else
            showiframe -p /boot/bootlogo.mvi &
         fi;;
      *) echo "[rcS] ERROR"
         echo "RESTART" > /dev/fplarge
         init 6;;
   esac
done

#never reached
echo "REBOOT" > /dev/fplarge
echo "[rcS] REBOOT TF77X0"
reboot -f
