#!/bin/sh
#Version 220610.1

echo "[rcS] Start"
echo "Fortis HS8200 Titan"

MODDIR=/lib/modules

insmod $MODDIR/e2_proc.ko

startconfig=/mnt/config/start-config
if [ ! -e "$startconfig" ]; then startconfig="/etc/titan.restore/mnt/config/start-config"; fi

. $startconfig
. /sbin/start-functioninsmod $MODDIR/e2_proc.ko

insmod $MODDIR/sata.ko

echo "[rcS] Init frontpanel"
if [ ! -e /dev/vfd ]; then
   mknod -m 0660 /dev/vfd c 147 0
fi
insmod $MODDIR/nuvoton.ko
insmod $MODDIR/simu_button.ko

if [ -e /var/etc/.first ]; then
   echo "Wait 1 min." > /dev/vfd
   echo "[rcS] Wait 1 minute"
   rm /var/etc/.first
   sleep 1
   touch /dev/.devfsd
else
   echo "Load 10" > /dev/vfd
   echo "[rcS] LOAD 10"
fi

/etc/init.d/mountvirtfs start

insmod $MODDIR/sata.ko

# Start automounter with umount timeout of 5 seconds
echo "[rcS] Starting automounter"
/etc/init.d/autofs start

echo "[rcS] Starting DEBUG Interface"
/etc/init.d/mountall start
/etc/init.d/hostname start

#if [ -d /dev/sda1/Recordings ]; then
#   echo "[rcS] Recordings directory found on /dev/sda1, checking..."
#   fsck.jfs -a /dev/sda1
#fi

echo -n "[rcS] Starting telnetd "
/usr/sbin/telnetd -l /bin/autologin
echo "with autologin"

echo "[rcS] Init stmfb (LOAD 9)"
echo "Load 9" > /dev/vfd
insmod $MODDIR/stmcore-display-sti7105.ko
insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m::pal:rgb:rgb # display1=720x576-16@50:1m::pal:cvbs
if [ -e /var/etc/.scart ]; then
   echo "$CMD [$INPUT] enable SCART (576i)"
   rmmod stmfb.ko
   insmod /lib/modules/stmfb.ko display0=720x576-32@50:1m::pal:cvbs
fi
stfbset -p
insmod $MODDIR/stm_v4l2.ko

echo "[rcS] Loading modules"

if [ ! -e /boot/audio.elf ] || [ ! -e /boot/video.elf ]; then
   echo "[rcS] Firmware(s) missing!"
   echo "FW MISSING!" > /dev/vfd
   sleep 5
fi

echo "[rcS] Load video firmware (LOAD 8)"
echo "Load 8" > /dev/vfd
/bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null

echo "[rcS] Load audio firmware (LOAD 7)"
echo "Load 7" > /dev/vfd
if [ -e /boot/audio_dts.elf ]; then
   /bin/ustslave /dev/st231-1 /boot/audio_dts.elf > /dev/null
else
   /bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null
fi

echo "[rcS] Init embx (LOAD 6)"
echo "Load 6" > /dev/vfd
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
insmod $MODDIR/mme_host.ko transport0=shm
insmod $MODDIR/mme_log.ko

echo "[rcS] Init AVS (LOAD 5)"
echo "Load 5" > /dev/vfd
insmod $MODDIR/avs.ko type=stv6418

player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
echo "[rcS] Init player $player (LOAD 4)"
echo "Load 4" > /dev/vfd
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stmvout.ko
insmod $MODDIR/stmvbi.ko

insmod $MODDIR/pseudocard.ko

if [ "$bootlogo" == 'y' ]; then
   if [ -e /mnt/swapextensions/etc/boot/bootlogo.jpg ]; then
     infobox 200 "nobox#/mnt/swapextensions/etc/boot/bootlogo.jpg" &
   else
      if [ -e /var/etc/boot/bootlogo.jpg ]; then
         infobox 200 "nobox#/var/etc/boot/bootlogo.jpg" &
      fi
   fi
fi

echo "[rcS] Init frontends"
insmod $MODDIR/frontend_platform.ko
insmod $MODDIR/socket.ko
insmod $MODDIR/lnbh221.ko
insmod $MODDIR/lnb_pio.ko
# DVB-S
insmod $MODDIR/avl2108.ko
# DVB-C
#insmod $MODDIR/tda10024.ko
# DVB-T
#insmod $MODDIR/cxd2820.ko

insmod $MODDIR/starci.ko #extmoduldetect=1
insmod $MODDIR/smartcard.ko

insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
#echo "pti return = $?"
if [ $? -ne '0' ]; then
   insmod $MODDIR/pti.ko
   echo "[rcS] Simple pti"
else
   echo "[rcS] Full feature pti"
fi
insmod $MODDIR/stm_monitor.ko
insmod $MODDIR/stmsysfs.ko
insmod $MODDIR/stmdvb.ko

echo "[rcS] Init player2 (LOAD 3)"
echo "Load 3" > /dev/vfd
insmod $MODDIR/player2.ko discardlateframe=0
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko
insmod $MODDIR/silencegen.ko

insmod $MODDIR/bpamem.ko

echo "Init HDMI-CEC"
if [ -e $MODDIR/cec.ko ]; then
   insmod $MODDIR/cec.ko activemode=1
fi

#if [ -e /boot/neutrinologo.mvi ]; then
#   showiframe -p /boot/neutrinologo.mvi &
#fi
#stfbcontrol a 0

if [ -e $MODDIR/exportfs.ko ]; then
   insmod $MODDIR/exportfs.ko
fi
if [ -e $MODDIR/cifs.ko ]; then
   insmod $MODDIR/cifs.ko
fi
if [ -e $MODDIR/ntfs.ko ]; then
   insmod $MODDIR/ntfs.ko
fi
if [ -e $MODDIR/tun.ko ]; then
   insmod $MODDIR/tun.ko
fi
if [ -e $MODDIR/usbserial.ko ]; then
   insmod $MODDIR/usbserial.ko
   if [ -e $MODDIR/ftdi.ko ]; then
      insmod $MODDIR/ftdi.ko
   fi
   if [ -e $MODDIR/pl2303.ko ]; then
      insmod $MODDIR/pl2303.ko
   fi
fi

echo "[rcS] Init remote control (LOAD 2)"
echo "Load 2" > /dev/vfd
/bin/evremote2 10 120 &

# Load modules from /var/etc/modules.extra
[ -f /var/etc/modules.extra ] && eval `sed -e 's/#.*//' -e '/^\s*$/d' -e 's/^\(.*\)/insmod \0;/' < /var/etc/modules.extra`

#stfbcontrol a 255

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "[rcS] Booting from NFS, do not set network"
else
   echo "[rcS] Setting wired network"
   if [ -e /mnt/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=`grep -c dhcp /mnt/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "[rcS] Starting DHCP"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
   fi
fi

#wlan=rtl8188cu
if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
   echo "No WLAN"
else
   insmod $MODDIR/$wlan.ko
   echo "$wlan WLAN"
#   echo "$wlan WLAN" > /dev/vfd
#   sleep 3
fi

# Try and synchronise time
if [ -h /usr/sbin/ntpd ]; then
   echo "Set internet time"
   (ntpd -n -p 0.europe.pool.ntp.org -q; /bin/fp_control -sst)
fi

echo "[rcS] Init portmap & ftp (LOAD 1)"
echo "LOAD 1" >/dev/vfd
/etc/init.d/portmap start
/etc/init.d/vsftpd start
/usr/sbin/inetd

echo "[rcS] Loading Titan"
echo "Loading Titan" > /dev/vfd

until false
do
   echo "[rcS] Starting Titan ->"
   /usr/local/bin/titan /mnt/config/titan.cfg
   rtv=$?
   echo "[rcS] Titan ended <- return value: " $rtv
   case "$rtv" in
      1) echo "[rcS] SHUTDOWN"
         echo "Shutdown" > /dev/vfd
         init 0
         /bin/fp_control -sst
         /bin/fp_control -e;;
      2) echo "[rcS] REBOOT"
         echo "Reboot" > /dev/vfd
         if [ -f /proc/stb/fp/force_restart ]; then
            echo 1 > /proc/stb/fp/force_restart
         fi
         /var/etc/autostart/start.sh reboot 
         /sbin/reboot;;
      3) echo "[rcS] RESTART Titan"
         echo "ReStrt Titan" > /dev/vfd
         ;;
      *) echo "[rcS] ERROR"
         echo "Error" > /dev/vfd
         init 6;;
   esac
done

#never reached
echo "[rcS] REBOOT HS8200"
echo "REBOOT HS8200" > /dev/vfd
init 6
