#!/bin/sh
#Version 151001.1

echo "Spark Tvheadend"

MODDIR=/lib/modules

echo "Init frontpanel"
insmod $MODDIR/aotom.ko
insmod $MODDIR/simu_button.ko

if [ -e /var/etc/.firstboot ]; then
   echo "1min" > /dev/vfd
   echo "WAIT 1 minute"
   rm /var/etc/.firstboot
   sleep 1
   touch /dev/.devfsd
else
   echo "LD10" > /dev/vfd
fi

/etc/init.d/mountvirtfs start
/etc/init.d/portmap start

insmod $MODDIR/e2_proc.ko

# Start automounter with umount timeout of 5 seconds
insmod $MODDIR/autofs4.ko
if [ -e /etc/init.d/automount ]; then
   /usr/sbin/automount --ghost --timeout=5 /tmp/autofs file /etc/auto.usb
fi

echo "Starting DEBUG Interface"
/etc/init.d/mountall start
/etc/init.d/hostname start

echo -n "Starting telnetd "
/usr/sbin/telnetd -l /bin/autologin
echo "with autologin"

echo "Init stmfb (LOAD 9)"
echo "LD 9" > /dev/vfd
insmod $MODDIR/stmcore-display-sti7111.ko
insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv

echo "Loading modules"

if [ ! -e /lib/firmware/audio.elf ] || [ ! -e /lib/firmware/video.elf ]; then
   echo "FIRMWARE!"
   echo "NOFW" > /dev/vfd
   sleep 5
fi

echo "Load audio firmware (LOAD 8)"
echo "LD 8" > /dev/vfd
if [ -e /lib/firmware/audio_dts.elf ]; then
   /bin/ustslave /dev/st231-1 /lib/firmware/audio_dts.elf > /dev/null
else
   /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf > /dev/null
fi

echo "Load video firmware (LOAD 7)"
echo "LD 7" > /dev/vfd
/bin/ustslave /dev/st231-0 /lib/firmware/video.elf > /dev/null

echo "Init embx (LOAD 6)"
echo "LD 6" > /dev/vfd
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
insmod $MODDIR/mme_host.ko transport0=shm

echo "Init AVS (LOAD 5)"
echo "LD 5" > /dev/vfd
insmod $MODDIR/avs.ko type=avs_pio

player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
echo "Init player $player (LOAD 4)"
echo "LD 4" > /dev/vfd
insmod $MODDIR/mmelog.ko
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko
insmod $MODDIR/stmvout.ko
insmod $MODDIR/stmvbi.ko
insmod $MODDIR/pseudocard.ko

insmod $MODDIR/stv090x.ko

insmod $MODDIR/smartcard.ko

#pti_arg="waitMS=20 videoMem=4096"
#echo "Full feature pti"
pti_arg=""
echo "Simple pti"
insmod $MODDIR/pti.ko $pti_arg
insmod $MODDIR/stm_monitor.ko
insmod $MODDIR/stmsysfs.ko
insmod $MODDIR/stmdvb.ko

echo "Init player2 (LOAD 3)"
echo "LD 3" > /dev/vfd
insmod $MODDIR/player2.ko
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko
insmod $MODDIR/silencegen.ko
insmod $MODDIR/bpamem.ko

if [ -e $MODDIR/cec.ko ];then
   insmod $MODDIR/cec.ko activemode=1
fi

if [ -e /boot/tvhlogo_720.mvi ]; then
   showiframe -p /boot/tvhlogo_720.mvi &
fi
echo "Init network (LOAD 2)"
echo "LD 2" >/dev/vfd

#   major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
#   rm -f /dev/sparkid
#   mknod /dev/sparkid c $major 0

#wlan=``
#if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
#   echo "No WLAN"
#else
#   insmod $MODDIR/$wlan.ko
#   echo "$wlan WLAN"
##   echo "$wlan WLAN" > /dev/vfd
##   sleep 3
#fi

if [ -e $MODDIR/ntfs.ko ]; then
   insmod $MODDIR/ntfs.ko
fi

if [ -e $MODDIR/cifs.ko ]; then
   insmod $MODDIR/cifs.ko
fi

echo "Init FTP (LOAD 1)"
echo "LD 1" > /dev/vfd
/etc/init.d/vsftpd start
/usr/sbin/inetd

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "Booting from nfs, don't set network"
else
   if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "Starting DHCP on eth0"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
   fi
fi
#Allow network to wake up and initialize
sleep 2
#Show last octet of IP address on frontpanel
ip=`ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p' | cut -d. -f4`
echo ".$ip" > /dev/vfd
sleep 3

# Do own extras
if [ -e /etc/ownscript.sh ]; then
   /etc/ownscript.sh &
fi

timefix tvheadend
date -s "201510011200"
# Try and synchronise time
if [ -e /sbin/ntpdate ]; then
   echo "Set internet time"
   (/sbin/ntpdate de.pool.ntp.org; /bin/fp_control -s `date +"%H:%M:%S %d-%m-%Y"`) &
else
   if [ -e /usr/sbin/time.sh ]; then
      echo "Use transponder time"
      /usr/sbin/time.sh &
   fi
fi

echo "Start Tvheadend" > /dev/vfd
echo "Start Tvheadend"

until false
do
   echo "Entering Tvheadend main loop"
   /usr/local/bin/tvheadend --http_port 80 -C
   rtv=$?
   echo "Tvheadend ended <- RTV: " $rtv
   case "$rtv" in
      0) echo "SHUTDOWN"
         echo "Shdn" > /dev/vfd
         init 0;;
      1) echo "REBOOT"
         echo "rebt" > /dev/vfd
         init 6;;
      *) echo "ERROR"
         echo "Err " > /dev/vfd
         init 6;;
   esac
done

#never reached
echo "rebt" > /dev/vfd
echo "REBOOT SPARK"
init 6
